### ISSUE TITLE
adding specufex to the requirements.txt

### ISSUE THREAD

**Issue by mdenolle** [SeisSCOPED/specufex#4]
Hello!
Could you write the specufex package in the seiscoped tutorial requirement.txt?

**Comment by mdenolle** [comment]
Hello again,

I see that requirements have specufex, but it seems that the tutorial image still does not contain the module.

Similarly, i tried to download the other latest image but was unable to import some basic modules (pandas, matploblib, seaborn) while other core modules were installed (h5py, specufex).

Would it be possible that the docker image of the package to include the modules necessary for the tutorials? I am not sure what the best practices are for these containers.


Happy to keep testing if that's helpful!
Cheers,
Marine

**Comment by ngroebner** [comment]
@mdenolle thank you for pointing that out! I will fix both of those issues. I appreciate you testing the builds. :)

Nate

**Comment by ngroebner** [comment]
fixed in specufex repository
