### ISSUE TITLE
M1 chip docker image

### ISSUE THREAD

**Issue by mdenolle** [SeisSCOPED/specufex#5]
Hello!

Would you mind making another docker image compatible with the new Apple M1 chip?
thank you so much!

**Comment by ngroebner** [comment]
Certainly - I will work on that!

**Comment by ngroebner** [comment]
@mdenolle an M1 image should be available now. If you have any problems getting it, let me know.

**Comment by ngroebner** [comment]
Closing this issue. If there are further problems, please reopen.
